//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta_Credito()
        {
            this.Tarjeta = new HashSet<Tarjeta>();
        }
    
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoMoneda { get; set; }
        public int CodigoSucursal { get; set; }
        public string Descripción { get; set; }
        public string IBAN { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal PagoMinimo { get; set; }
        public decimal PagoContado { get; set; }
        public string Estado { get; set; }
        public int CodigoTarjeta { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta { get; set; }
        public virtual Tarjeta Tarjeta1 { get; set; }
    }
}
