//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Credito
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoMoneda { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoTarjeta { get; set; }
        public string Descripción { get; set; }
        public string IBAN { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal PagoMinimo { get; set; }
        public decimal PagoContado { get; set; }
        public string Estado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
