//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Codigo { get; set; }
        public int CodigoServicio { get; set; }
        public int CodigoTarjeta { get; set; }
        public System.DateTime Fechahora { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
